# Generated by Django 5.2.9 on 2025-12-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('spesialisasi', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('keluhan', models.TextField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.pasien')),
            ],
        ),
    ]
